#!/bin/sh

set -e

echo '+SQLX_OFFLINE=true cargo check --all'
SQLX_OFFLINE=true cargo check --all

echo '+cargo sqlx prepare --workspace --check'
cargo sqlx prepare --workspace --check

echo '+cargo +nightly fmt --all -- --check'
cargo +nightly fmt --all -- --check

echo '+cargo spellcheck --cfg=.spellcheck.toml'
cargo spellcheck --cfg=.spellcheck.toml -m 1

echo '+SQLX_OFFLINE=true cargo clippy --all -- -D warnings'
SQLX_OFFLINE=true cargo clippy --all -- -D warnings

echo '+cargo machete'
cargo machete

echo '+cargo deny check all'
cargo deny check all

echo '+cargo test --all'
cargo test --all

# echo '+cargo tarpaulin'
# cargo tarpaulin
