#!/bin/bash

export APP_OPENSTACK__KEYSTONE_ENDPOINT="${OS_AUTH_URL}"
export APP_OPENSTACK__USERNAME="${OS_USERNAME}"
export APP_OPENSTACK__PASSWORD="${OS_PASSWORD}"
export APP_OPENSTACK__PROJECT="${OS_PROJECT_NAME}"
export APP_OPENSTACK__PROJECT_ID="${OS_PROJECT_ID}"
export APP_OPENSTACK__DOMAIN="${OS_USER_DOMAIN_NAME}"
export APP_OPENSTACK__DOMAIN_ID="${OS_PROJECT_DOMAIN_ID}"
